language: java
jdk:
- oraclejdk8

deploy:
  provider: s3
  access_key_id: AKIAJGGH7AQU4KMZTW6A
  secret_access_key:
    secure: Wkusjr/8AHRgfonghjg6SpIvmQ7MiX9sjEJW/R35bcagRqRgZjHVcCqIDmfSnOfCJ1zbdpIEFViu1ZhBAIvD9VHHWibdRIow0IRRT9bDImNF3EOX3Vucj+qdSecjjTT2P52IdukTLYGQKkq6p/IWEdlYv+Cb4Y/CRQ0DK1WshCdG8Z6WvMxHKtvJPOT4DQ9Nnl3YbtmxRVIdKnB4bKPCY3jMsrqZXqtvYtwh/eaj5JjGMu8N7qZdZIL8cQ7EN0Cco1PLJpRge6F5PS0JBge0TV8+5LppphZU9fgaFRzOWPpJ3Ikd7zlVkIjlycfjsFcaEzGjQ9L8cxZHAJKC/LE14IHQ9YK/z24QiFnO3dnjDkbz4edQ+767mSaKCOsNbkU+O4tEUrT4ssIUcVD7grRvNwG2ayhfwFCZCczofJjPAryYC0XkXlWbHgQPm3jqY1CanHcHLDuUx6J0uxyfp1mg+D0v6lMbf9hNkOdsfZc7wzkdvwSkZTYMIaw/RSMrHgo4gbpxyKxFNn7rzNxED7hxFhaLFd1GfW3/f97M50/RcPlzkMJoiVaDLfqiODb/BaRzJvBYZqHRHp3Jb6zL1gebwcYKtjb9YSJLc00OkMQNj0ibqGa8jTA/wMlAoA13dSyTmLbsWaxSgjxL1LNdtSbrMOhLzYW+28GEYR++iFEq0io=
  bucket: ro.mihalea.barebones
